# aca definimos los contenedores q vamos a levantar, cada servicio es un contenedor
services:

  db:
    # usamos la imagen oficial de postgres, con la version 15
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # esta variable postgres_db es importante,
      # porq le dice a la imagen oficial de postgres que cree una db con ese nombre al iniciar el contenedor por primera vez
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # persiste los datos de postgres localmente
      - ./.volumes/postgres/data:/var/lib/postgresql/data
      # ejecuta el init.sql al crear el contenedor por primera vez
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - prode-net

  backend:
    # construimos la imagen a partir del Dockerfile en la carpeta backend
    build: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      # sincroniza el codigo local con el contenedor en tiempo real
      # cuando guardas un archivo, nodemon lo detecta y reinicia el servidor
      - ./backend:/app
      # evita que el volumen anterior pise el node_modules del contenedor
      - /app/node_modules
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    # levanta la db antes que el backend
    depends_on:
      - db
    networks:
      - prode-net

  frontend:
    # construimos la imagen a partir del Dockerfile en la carpeta frontend
    build: ./frontend
    # puerto 80 estandar, accesible desde http://localhost
    ports:
      - "80:80"
    # sincroniza el frontend local con el contenedor
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - prode-net

# red compartida entre los 3 contenedores
networks:
  prode-net: