#aca definimos los contenedores q vamos a levantar, cada servicio es un contenedor
services:

  db:
    # usamos la imagen oficial de postgres, con la version 15
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # esta variable postgres_db es importante, 
      # porq le dice a la imagen oficial de postgres que cree una db con ese nombre al iniciar el contenedor por primera vez
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
    # el primer volumen es para persisitr los datos de la db de postgres localmente
      - ./.volumes/postgres/data:/var/lib/postgresql/data
    # el segundo volumen es para ejecutar el script de inicializacion de la db al levantar el contenedor, 
    # que ejecuta el script init.sql que se encuentra en la carpeta db/init.sql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # conectamos el contenedor a la red prode-net, que es la red que vamos a usar para que los contenedores se comuniquen entre si
    networks:
      - prode-net

  backend:
  # aca usamos build en vez de image porq no usamos una imagen prefabricada, sino que construimos la imagen 
  # a partir del dockerfile que esta en la carpeta backend
    build: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      # sincroniza el codigo local con el contenedor en tiempo real
      # cuando guardas un archivo, nodemon lo detecta y reinicia el servidor
      - ./backend:/app
      - /app/node_modules
      # evita que el volumen anterior pise el node_modules del contenedor
          
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}      
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    # el depends_on le esta diciendo a docker que levante el contenedor de la db antes que elk bakcend
    # para que el backend pueda conectarse a la db sin problemas, 
    # sino el backend intentaria conectarse a la db antes de que este levantada y daria error
    depends_on:
      - db
    networks:
      - prode-net

  frontend:
  # igual q bckend consturimos la imagen a partir del dockerfile que esta en la carpeta frontend
    build: ./frontend
    # puerto 80 estandar para front , lo mapeo al puerto 80 para poder acceder escribiendo http://localhost en el navegador
    ports:
      - "80:80"

    # agrego volume para no rebuildear cada vez q cambio archivos
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - prode-net
# aca definimos la red compartida entre los 3 contenedores, para que se puedan comunicar entre si
networks:
  prode-net: